import pygal
def buy(year):
    sumbuy = 0
    for i in year:
        i = i.split()
        sumbuy += float(i[1])
    return sumbuy
def chart():
    year0 = buy(open("../data/data0.txt", "r", encoding="utf-8"))
    year1 = buy(open("../data/data1.txt", "r", encoding="utf-8"))
    year2 = buy(open("../data/data2.txt", "r", encoding="utf-8"))
    year3 = buy(open("../data/data3.txt", "r", encoding="utf-8"))
    year4 = buy(open("../data/data4.txt", "r", encoding="utf-8"))
    year5 = buy(open("../data/data5.txt", "r", encoding="utf-8"))
    year6 = buy(open("../data/data6.txt", "r", encoding="utf-8"))
    year7 = buy(open("../data/data7.txt", "r", encoding="utf-8"))
    year8 = buy(open("../data/data8.txt", "r", encoding="utf-8"))
    year9 = buy(open("../data/data9.txt", "r", encoding="utf-8"))
    year10 = buy(open("../data/data10.txt", "r", encoding="utf-8"))
    year11 = buy(open("../data/data11.txt", "r", encoding="utf-8"))
    year12 = buy(open("../data/data12.txt", "r", encoding="utf-8"))
    year13 = buy(open("../data/data13.txt", "r", encoding="utf-8"))
    year14 = buy(open("../data/data14.txt", "r", encoding="utf-8"))
    year15 = buy(open("../data/data15.txt", "r", encoding="utf-8"))
    year16 = buy(open("../data/data16.txt", "r", encoding="utf-8"))
    year17 = buy(open("../data/data17.txt", "r", encoding="utf-8"))
    chart_buy = pygal.Bar()
    chart_buy.title = "Buy in 2000 to 2017"
    chart_buy.add('Buy in 2000', year0)
    chart_buy.add('Buy in 2001', year1)
    chart_buy.add('Buy in 2002', year2)
    chart_buy.add('Buy in 2003', year3)
    chart_buy.add('Buy in 2004', year4)
    chart_buy.add('Buy in 2005', year5)
    chart_buy.add('Buy in 2006', year6)
    chart_buy.add('Buy in 2007', year7)
    chart_buy.add('Buy in 2008', year8)
    chart_buy.add('Buy in 2009', year9)
    chart_buy.add('Buy in 2010', year10)
    chart_buy.add('Buy in 2011', year11)
    chart_buy.add('Buy in 2012', year12)
    chart_buy.add('Buy in 2013', year13)
    chart_buy.add('Buy in 2014', year14)
    chart_buy.add('Buy in 2015', year15)
    chart_buy.add('Buy in 2016', year16)
    chart_buy.add('Buy in 2017', year17)
    chart_buy.render_to_file('../img/buy.svg')
chart()
