import pygal
def sell(year):
    sumsell = 0
    for i in year:
        i = i.split()
        sumsell += float(i[2])
    return sumsell
def chart():
    year0 = sell(open("../data/data0.txt", "r", encoding="utf-8"))
    year1 = sell(open("../data/data1.txt", "r", encoding="utf-8"))
    year2 = sell(open("../data/data2.txt", "r", encoding="utf-8"))
    year3 = sell(open("../data/data3.txt", "r", encoding="utf-8"))
    year4 = sell(open("../data/data4.txt", "r", encoding="utf-8"))
    year5 = sell(open("../data/data5.txt", "r", encoding="utf-8"))
    year6 = sell(open("../data/data6.txt", "r", encoding="utf-8"))
    year7 = sell(open("../data/data7.txt", "r", encoding="utf-8"))
    year8 = sell(open("../data/data8.txt", "r", encoding="utf-8"))
    year9 = sell(open("../data/data9.txt", "r", encoding="utf-8"))
    year10 = sell(open("../data/data10.txt", "r", encoding="utf-8"))
    year11 = sell(open("../data/data11.txt", "r", encoding="utf-8"))
    year12 = sell(open("../data/data12.txt", "r", encoding="utf-8"))
    year13 = sell(open("../data/data13.txt", "r", encoding="utf-8"))
    year14 = sell(open("../data/data14.txt", "r", encoding="utf-8"))
    year15 = sell(open("../data/data15.txt", "r", encoding="utf-8"))
    year16 = sell(open("../data/data16.txt", "r", encoding="utf-8"))
    year17 = sell(open("../data/data17.txt", "r", encoding="utf-8"))
    chart_sell = pygal.Bar()
    chart_sell.title = "Sell in 2000 to 2017"
    chart_sell.add('Sell in 2000', year0)
    chart_sell.add('Sell in 2001', year1)
    chart_sell.add('Sell in 2002', year2)
    chart_sell.add('Sell in 2003', year3)
    chart_sell.add('Sell in 2004', year4)
    chart_sell.add('Sell in 2005', year5)
    chart_sell.add('Sell in 2006', year6)
    chart_sell.add('Sell in 2007', year7)
    chart_sell.add('Sell in 2008', year8)
    chart_sell.add('Sell in 2009', year9)
    chart_sell.add('Sell in 2010', year10)
    chart_sell.add('Sell in 2011', year11)
    chart_sell.add('Sell in 2012', year12)
    chart_sell.add('Sell in 2013', year13)
    chart_sell.add('Sell in 2014', year14)
    chart_sell.add('Sell in 2015', year15)
    chart_sell.add('Sell in 2016', year16)
    chart_sell.add('Sell in 2017', year17)
    chart_sell.render_to_file('../img/sell.svg')
chart()
